### ISSUE TITLE
question

### ISSUE THREAD

**Issue by chris-kruining** [MortalFlesh/MFCollectionsPHP#26]
Hey,

I'm implementing my version of a collection and today I introduced lazy method calls. however when I measure lazy v.s. non-lazy, non-lazy wins every time with quite a large margin. I am very curious how and by what margin your lazy mapping improves performance :D

**Comment by MortalFlesh** [comment]
Hey,

well I've checked out your code and if I understand it correctly, you iterate through `chain` and applies functions as it would be applied in `non-lazy` collection.

But in my collections, it is composed in other direction. If you check `apply` method here https://github.com/MortalFlesh/MFCollectionsPHP/blob/master/Collection/Mutable/ListCollection.php#L62-L74 it is iterating through the collection only **once**, so it doesn't really matter how many times you `map` or `filter` collection, because those functions will be applied in one collection loop.

So if you will have following pseudo code
```php
$add1 = function($i) {return $i + 1;};

$col = new Collection([1,2,3,4,5]);
$col->map($add1);
$col->map($add1);
$col->map($add1);
$col->map($add1);
$col->map($add1);
$col->toArray();
```
In your collections it will iterate through functions, so you iterate 25 times via every item.

But I will stack all callbacks in one loop, so I will iterate just 5 times.

So as far as I see it, you `lazy` is not so `lazy` :)

**Comment by chris-kruining** [comment]
I see, thanks, I thought as much, looking at you implementation you do exactly what I avoided doing. what you do is 'parse' the result of every 'lazy-able' function by hand to see if you should continue with that particular item or not, since you have 2 'lazy-able' functions (map, filter) this is very feasible in the implementation. In my case I have like 20 'lazy-able' functions that each may or may not return 0 or many new items and some might need the result of previous iterations to work, this would become a giant mess if I were to try and interweave these functions, maybe I could try to define a subset of these 'lazy-able' functions that could simply be executed and once's that need previous results... any thoughts?

**Comment by MortalFlesh** [comment]
Well yes you are right about the feasibility of my implementation, because I dont see my Collections as lazy.. I simply have lazy `map` and `filter` methods.

I'll try to think about your `lazy` collections in general.. 

But for now, you can stick with 3 function types 
- `map` - same number of items
- `filter` - same or less items
- `add` - same or more items
and by this pattern you might be able to use similar pattern I have.
